name: zz - Reusable Test

on:
  workflow_call:

jobs:
  test:
    name: Run Tests
    # The type of runner that the job will run on any runner with node will work
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Cache
        uses: actions/cache@v3
        with:
          path: .jest-cache
          key: ${{ runner.os }}-jest-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-jest-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-jest-
      
      - name: Node Modules Cache
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-
      
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      
      - name: Yarn Install
        if: steps.node-cache.outputs.cache-hit != 'true' || steps.setup-node.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Setup Test env
        run: cp .env.integration .env.integration.local

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EXTERNAL_SUPPORT_GRAPHQL_ACCESS_TOKEN: ${{ secrets.EXTERNAL_SUPPORT_GRAPHQL_ACCESS_TOKEN }}
        run: yarn test --coverage 

      - name: Remove unused coverage files
        run: rm -rf coverage/clover.xml coverage/coverage-final.json coverage/lcov-report
      
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage/
